# -*- coding: utf-8 -*-
"""weather_automation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h3FrcYXDynvoO43HbuM9_ZPUhPNQKbwh
"""

import requests

def get_weather(city):
    url = f"https://wttr.in/{city}?format=j1"

    try:
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()

        temperature = data["current_condition"][0]["temp_C"]
        humidity = data["current_condition"][0]["humidity"]
        description = data["current_condition"][0]["weatherDesc"][0]["value"]

        print(f"\nWeather Report for {city}")
        print(f"Temperature: {temperature}°C")
        print(f"Humidity: {humidity}%")
        print(f"Condition: {description}")

    except Exception as e:
        print("Error fetching weather:", e)

city = input("Enter city name: ")
get_weather(city)

